language: node_js

node_js:
  - "8"
  - "9"

sudo: false

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn run test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
